spring.application.name=cns-backend
spring.config.import=optional:classpath:application-local.properties,optional:classpath:api.properties

# Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
spring.jwt.secret=${JWT_SECRET}

# File Upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Google API
google.api.key=${GOOGLE_API_KEY:}
google.translate.url=https://translation.googleapis.com/language/translate/v2

# OpenAI API
openai.api.key=${OPENAI_API_KEY:}
openai.api.url=https://api.openai.com/v1/images/generations
